#pragma once

enum class BodyNameVersion
{
  INVALID_VALUE = -1,
  CBBE_3BBB_3BA_1_50,
  CBBE_3BBB_3BA_1_51_TO_1_55,
  CBBE_SMP_3BBB_1_2_0,
  BHUNP_3BBB_2_20,
  BHUNP_3BBB_ADVANCED_2_20,
  BHUNP_3BBB_ADVANCED_VER_2_2_20,
  BHUNP_BBP_2_20,
  BHUNP_BBP_ADVANCED_2_20,
  BHUNP_TBBP_2_20,
  BHUNP_TBBP_ADVANCED_2_20,
  BHUNP_3BBB_2_25,
  BHUNP_3BBB_ADVANCED_2_25,
  BHUNP_3BBB_ADVANCED_VER_2_2_25,
  BHUNP_BBP_2_25,
  BHUNP_BBP_ADVANCED_2_25,
  BHUNP_TBBP_2_25,
  BHUNP_TBBP_ADVANCED_2_25,
  CBBE_3BBB_3BA_2_02_TO_2_04,
  CBBE_3BBB_3BA_2_06,
  BHUNP_3BBB_2_30,
  BHUNP_3BBB_ADVANCED_2_30,
  BHUNP_3BBB_ADVANCED_VER_2_2_30,
  BHUNP_BBP_2_30,
  BHUNP_BBP_ADVANCED_2_30,
  BHUNP_TBBP_2_30,
  BHUNP_TBBP_ADVANCED_2_30,
  BHUNP_3BBB_ADVANCED_VER_2_NEVERNUDE_2_25,
  BHUNP_3BBB_ADVANCED_VER_2_NEVERNUDE_2_30,
  BHUNP_3BBB_2_31,
  BHUNP_3BBB_ADVANCED_2_31,
  BHUNP_3BBB_ADVANCED_VER_2_2_31,
  BHUNP_BBP_2_31,
  BHUNP_BBP_ADVANCED_2_31,
  BHUNP_TBBP_2_31,
  BHUNP_TBBP_ADVANCED_2_31,
  BHUNP_3BBB_2_35,
  BHUNP_3BBB_ADVANCED_2_35,
  BHUNP_3BBB_ADVANCED_VER_2_2_35,
  BHUNP_BBP_2_35,
  BHUNP_BBP_ADVANCED_2_35,
  BHUNP_TBBP_2_35,
  BHUNP_TBBP_ADVANCED_2_35,
  MIMIR_EBONIC_BODY_1_2
};

enum class BodyName
{
  CBBE_3BBB_3BA,
  CBBE_SMP_3BBB,
  BHUNP_3BBB,
  BHUNP_3BBB_ADVANCED,
  BHUNP_3BBB_ADVANCED_VER_2,
  BHUNP_BBP,
  BHUNP_BBP_ADVANCED,
  BHUNP_TBBP,
  BHUNP_TBBP_ADVANCED,
  BHUNP_3BBB_ADVANCED_VER_2_NEVERNUDE,
  MIMIR_EBONIC_BODY
};

enum class ApplicationLanguage
{
  ENGLISH,
  FRENCH,
  CHINESE_TRADITIONAL
};

enum class GUITheme
{
  WINDOWS_VISTA,
  MITSURIOU_BLACK_THEME,
  MITSURIOU_DARK_THEME,
  MITSURIOU_LIGHT_THEME,
  ALEXHUSZAGH_BREEZE_DARK,
  ALEXHUSZAGH_BREEZE_LIGHT,
  PAPER_DARK,
  PAPER_LIGHT,
  PAPER_BLACK_MONO,
  PAPER_WHITE_MONO
};

enum class WindowOpeningMode
{
  MINIMIZED,
  WINDOWED,
  MAXIMIZED
};

enum class StartupAction
{
  OPEN_WELCOME_SCREEN,
  CHECK_FOR_UPDATES,
  SKIP_UPDATE_CHECKS
};

enum class AssistedConversionRole
{
  IGNORED,
  BODY,
  FEET,
  HANDS,
  SKELETON
};

enum class ButtonClicked
{
  YES,
  NO,
  CLOSE_WINDOW,
  OTHER
};

enum class BodyPartType
{
  BODY,
  FEET,
  HANDS,
  BEAST_HANDS
};

enum class ApplicationVersionRelative
{
  OLDER,
  EQUIVALENT,
  NEWER
};
